name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Generate token
      id: token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APPLICATION_ID }}
        private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login --username docker-test-org --password ${{ steps.token.outputs.token }} ghcr.io
        docker build -t ghcr.io/docker-test-org/hello-world:latest .
        docker push ghcr.io/docker-test-org/hello-world:latest
